### PR TITLE
aman kumar portfolio website

### LINKED ISSUE #2: Portfolio - Aman Kumar
Can i contribute my portfolio website?

### PR DESCRIPTION
**Pull request by amankumar11**
fixes #2 
https://amankumar11.github.io/Portfolio-website/
@itsmnsi pls review the changes and merge the PR with label hacktoberfest-accepted

### CODE REVIEW

**Comment by itsmnsi** [comment]
hacktoberfest-accepted

**Comment by itsmnsi** [comment]
Can you please tell me its accepted for hacktoberfest or not?

**Comment by amankumar11** [comment]
image
Yes, it's accepted and will mature in 14 days !

**Comment by itsmnsi** [comment]
Great Thanks for contributing!!! Suggest for others to contribute n star the repo :))

**Comment by amankumar11** [comment]
Yaa sure !

**Pull request merged**
